- README.md
Markdown headers require a space after the hashes to be properly parsed. This commit will add those spaces. 
Before:
After:
> Fix markdown formatting for headers in readme

- configure.ac
- src/Makefile.am
Feednix cannot add items for entries with wide (a.k.a. multi-byte) characters.  It fails on creating items using `new_item`, which returns `nullptr` due to `E_BAD_ARGUMENT`.  This pull requests replaces libraries with ones supporting wide characters.
I confirmed that entries with wide characters were shown after this change on Ubuntu 20.04.1 LTS.
> Support wide characters

- src/FeedlyProvider.cpp
`make` with g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0 shows following warnings about calling a deprecated function.  This pull request replaces the function with its successor.
```
FeedlyProvider.cpp: In member function ‘void FeedlyProvider::authenticateUser()’:
FeedlyProvider.cpp:51:63: warning: ‘std::string Json::Reader::getFormatedErrorMessages() const’ is deprecated: Use getFormattedErrorMessages() instead. [-Wdeprecated-declarations]
51 |                 log_stream << reader.getFormatedErrorMessages() << std::endl;
|                                                               ^
In file included from /usr/include/jsoncpp/json/json.h:11,
from FeedlyProvider.cpp:9:
/usr/include/jsoncpp/json/reader.h:114:18: note: declared here
114 |   JSONCPP_STRING getFormatedErrorMessages() const;
| …
```
> Replace deprecated methods

- src/Makefile.am
- src/main.cpp
Feednix cannot complete the initial launch due to an error on Ubuntu 20.04.1 LTS because its `mkdir` doesn't support `-P` option.
```
mkdir: invalid option -- 'P'
Try 'mkdir --help' for more information.
```
This pull request rewrites some file operations with `std::filesystem` (which requires C++17 or above) to make them portable.
I confirmed that Feednix with this change was able to launch even when `~/.config/feednix` was missing.
> Fix an initial launch failure due to an unsupported mkdir option

- src/FeedlyProvider.cpp
When Feednix launches for the first time, it tries to open the Feedly authentication page with `xdg-open`.  However, the command doesn't redirect the output correctly on Ubuntu 20.04.1 LTS.  That results in launching interactive w3m in a non-desktop (i.e. CUI) session.  w3m conflicts with Feednix waiting for the user ID input.  The console becomes uncontrollable.
This pull request launches `xdg-open` as a foreground application to get the redirect work.  In addition, Feednix shows the Feedly authentication page to let the user open it manually in case of any browser issue.
I confirmed with this change:
- Feednix launched www-browser (w3m) which terminates immediately in a console session
- Feednix launched the preferred browser in a XFCE4 terminal
- The launched browser didn't block …
> Ask the user to open the Feedly authentication page when Feednix cannot

- README.md
- config.json
- src/CursesProvider.cpp
- src/CursesProvider.h
Feednix currently marks an article as read on showing it.  However, I personally prefer marking articles as read explicitly.  Feedly has "Auto-Mark As Read On Scroll" setting for that.
This pull request adds "seconds_to_mark_as_read" setting.  Its value is an integer indicating how many seconds the article should have been shown for when Feednix marks the current article as read automatically.  The default value is 0, meaning that an article will be marked as read whenever it's selected (~= the behavior without this change).  A negative value indicates that an article will never be marked as read unless the user explicitly does that by "r" key.
I confirmed that:
- 'seconds_to_mark_as_read: 0' always marks a selected item as read.  That now happens when the selection changes or Feednix …
> Add a setting to configure seconds to mark an article as read

- src/FeedlyProvider.cpp
Feednix cannot open entries of some feeds (e.g. YouTube feeds).  It uses `originId` in [Feedly Entries API](https://developer.feedly.com/v3/entries/), which is not necessarily a URL.
This pull request uses an alternate URL for "text/html".  It should always have the URL of the original web page.
I confirmed that Feednix with this change was able to open an entry of a YouTube feed by "o" key.
> Use alternate URL

- src/CursesProvider.cpp
- src/CursesProvider.h
- src/main.cpp
Feednix causes a segmentation fault when it's started with "-h" command line option because its cleanup logic tries to access a non-initialized pointer of `CursesProvider`.
This pull request moves the cleanup logic of `CursesProvider` to its destructor and initializes the pointer in a RAII (Resource Acquisition Is Initialization) approach.
I confirmed that `./feednix -h` with this change terminated successfully
> Fix a segmentation fault on -h

- src/CursesProvider.cpp
- src/FeedlyProvider.cpp
- src/FeedlyProvider.h
During working on another pull request, Feednix started to crash on its launch.  It was because Feedly API reached its limit and started returning an error response which Feednix couldn't recognize.
This pull request merges different places calling Feedly APIs into `retrieve_curl` with a new handling logic for error responses.  In case of any error, it throws an exception.  `CursesProvider` handles it and shows its message as a status message.
I confirmed:
- Marking, unmarking, saving, unsaving entries keeps working same when Feedly API calls are successful.
- Feednix shows an error status message when Feedly API reaches its limit.
> Handle Feedly API error

- src/CursesProvider.cpp
- src/CursesProvider.h
Building Feednix with g++ 9.3.0 on Ubuntu 20.04.1 shows warnings on `ARRAY_SIZE`.  The calculation is wrong or at least difficult to understand.
```
CursesProvider.cpp:21:34: warning: division ‘sizeof (ITEM** {aka tagITEM**}) / sizeof (ITEM* {aka tagITEM*})’ does not compute the number of array elements [-Wsizeof-pointer-div]
21 | #define ARRAY_SIZE(a) (sizeof(a) / sizeof(a[0]))
|                        ~~~~~~~~~~^~~~~~~~~~~~~~
```
This pull request replaces C++ arrays with `std::vector`.  It also fixes a leak of `postsItems` when post items are refreshed by choosing another category.
I confirmed warnings were gone and Feednix worked without any noticeable problem on starting, terminating, marking articles as read, or navigating across categories.
> Replace C arrays with std::vector

- src/CursesProvider.cpp
Building Feednix with g++ 9.3.0 on Ubuntu 20.04.1 LTS shows warnings on unused variables.
```
CursesProvider.cpp: In member function ‘void CursesProvider::ctgMenuCallback(char*)’:
CursesProvider.cpp:470:21: warning: variable ‘starty’ set but not used [-Wunused-but-set-variable]
470 |         int startx, starty, height, width;
|                     ^~~~~~
CursesProvider.cpp: In member function ‘void CursesProvider::win_show(WINDOW*, char*, int, bool)’:
CursesProvider.cpp:654:21: warning: variable ‘starty’ set but not used [-Wunused-but-set-variable]
654 |         int startx, starty, height, width;
|                     ^~~~~~
CursesProvider.cpp:654:29: warning: variable ‘height’ set but not used [-Wunused-but-set-variable]
654 |         int startx, starty, height, width;
| …
```
> Mark unused variables

- src/CursesProvider.cpp
During a feature development, I found a segmentation fault on creating the category menu.  `CursesProvider::createCategoriesMenu()` tries to set a menu option for the uninitialized post menu.
This pull request changes the method to set a menu option for the category menu instead.
I confirmed that Feednix with this change was able to launch, view articles, and mark articles as read without any issue.
> Fix menu initialization

- src/FeedlyProvider.cpp
- src/FeedlyProvider.h
Feednix generates a log file under the current directory with a random name when it hits a fatal error.  It's presumably because of a wrong use of `std::string(...).c_str()` which may free the buffer just after the call.
This pull request changes to keep the log file path as `FeedlyProvider::logPath` so that the path character buffer is always valid during the Feedly provider lifetime.
I confirmed that Feednix with this change appended error logs to `~\.config\feednix\log.txt` when `~\.config\feednix\config.json` was illformed.
> Fix a bug where Feednix writes error logs to a random file

- src/FeedlyProvider.cpp
- src/FeedlyProvider.h
According to `man curl_easy_escape`, we must call `curl_free` for every string returned from `curl_easy_escape`.  However, currently Feednix doesn't do that.
This pull request adds a type named `CurlString` based on `std::unique_ptr` to ensure calling `curl_free` when a string returned from `curl_easy_escape` becomes unnecessary.
I confirmed that Feednix with this change was still able to show articles in "All" category without any issue.
> Call curl_free for every curl_easy_escape string

- config.json
- src/CursesProvider.cpp
- src/CursesProvider.h
Feednix uses w3m for opening a post in the console.  I personally prefer another text browser such as [rdrview](https://github.com/eafer/rdrview) to read the content in a clean view.
To support the scenario, this pull request adds a new option named `text_browser` to specify the default text browser to open a post in the console.  It also supports `BROWSER` environment variable to override the default text browser.  The priority order is as follows.
1. Use `BROWSER` environment variable if it's set.
2. Use `text_browser` option if it's set.
3. Use `w3m`.
This pull request also introduces a consolidated logic for previewing and opening a post with some error handling.
I confirmed that:
- Feednix opens a post with a text browser specified by `BROWSER` environment variable and ignores …
> Add text_browser option

- src/CursesProvider.cpp
- src/CursesProvider.h
Pressing 'r' when the category menu is selected in Feednix shows the current category as read (i.e. render it in dark yellow) but it actually does nothing.  In addition, Feednix crashes due to a segmentation fault on pressing some keys when there is no post in the current category.
This pull request ignores some key bindings supported only in a specific menu of Feednix when the correct menu is not selected.  It also adds check the existence of the current item to avoid segmentation faults.  Lastly, it eliminates unnecessary string duplications that never get freed.
I confirmed that:
- Pressing 'o', 'O', 'r', 'u', 's', and 'S' did nothing when the category menu is selected.
- Pressing 'o', 'O', 'r', 'u', 's', and 'S' keeps the current behavior when the post menu is selected.
- Pressing …
> Ignore unsupported key bindings

- src/CursesProvider.cpp
- src/CursesProvider.h
- src/FeedlyProvider.cpp
- src/FeedlyProvider.h
- src/main.cpp
Building Feednix with g++ 9.3.0 on Ubuntu 20.04.1 LTS shows the following error.
```
CursesProvider.cpp: In member function ‘void CursesProvider::postsMenuCallback(ITEM*, bool)’:
CursesProvider.cpp:639:15: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
639 |         system(std::string("rm " + TMPDIR + "/preview.html 2> /dev/null").c_str());
|         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
This pull request makes following changes.
- Replace `system("rm ...")` with `std::filesystem::remove` to remove a temporary file in a more portable way.
- Replace `TMPDIR` global string with `TMPDIR` static path to be passed to `CursesProvider` and `FeedlyProvider` as their constructor …
> Replace rm and TMPDIR using std::filesystem

- src/CursesProvider.cpp
- src/FeedlyProvider.cpp
- src/FeedlyProvider.h
Feednix uses raw pointers. However, they're sometimes not freed and causing memory leaks.
This pull request replaces raw pointers with const references.
I confirmed that Feednix with this change was able to do followings:
> Replace pointers with references

- ChangeLog
- configure.ac
- src/Makefile.am
`make distcheck` fails on Ubuntu 20.04.1 LTS. It's because `Makefile.am` doesn't list header files while ["All header files must be listed somewhere"](https://www.gnu.org/software/automake/manual/html_node/Headers.html).
This pull request adds header files in `feednix_SOURCES` defined in `Makefile.am`. It also updates the distribution version to 0.9.3.
I confirmed that `make` and `make distcheck` succeeded on Ubuntu 20.04.1 LTS.
> Update the version to 0.9.3 fixing distcheck

- .github/workflows/c-cpp.yml
- README.md
- src/Makefile.am
This pull request adds a GitHub Action to re-enable the continuous integration build for master branch. It also adds  `-I/usr/include/jsoncpp` to `feednix_CPPFLAGS` for making a build on Ubuntu succeed by default.
Since Travis CI stopped working, Feednix has no continuous integration build. Re-enabling it using GitHub Action will help developers avoid breaking the build and installation.
I confirmed that [the same GitHub Action succeeded on my fork](https://github.com/masaru-iritani/Feednix/pull/3/checks?check_run_id=1961040390). I also confirmed that `./autogen.sh && ./configure && make && make distcheck && sudo make install` succeeded on Ubuntu 20.04.1 LTS.
> Add GitHub Action for the continuous integration build

- src/FeedlyProvider.cpp
Feednix uses `ctime` for outputting the current time to a log file when an error happened. However, [the CodeQL analysis](https://codeql.github.com/codeql-query-help/cpp/cpp-potentially-dangerous-function/) warns its use because it's not thread-safe. In addition, `ctime` is marked as obsolete according to [`man 3 ctime_r`](https://man.archlinux.org/man/core/man-pages/ctime_r.3.en).
This pull request replaces `ctime` with `localtime_r` and `strftime`. We will be able to enable the CodeQL analysis without any warning after the change. `ctime_r` is not used because it's marked as obsolete, too.
> Replace ctime with thread-safe functions

- src/CursesProvider.cpp
- src/CursesProvider.h
Feednix uses `strdup` in several places. However, it's unnecessary because the final consumer of strings, `mvwprintw` doesn't require the buffer duplication. In addition, duplicated buffers are not freed, and causing memory leaks.
This pull request removes unnecessary `strdup` and updates methods to handle constant characters. It also includes method renames to follow a single naming convention (camelCase).
I confirmed that Feednix with this change can render panel labels correctly when it launched and came back from `w3m` previewing a post.
> Remove unnecessary strdup

- src/CursesProvider.cpp
- src/CursesProvider.h
Feednix shows "All Posts Read" message when there is no unread post in the current category. However, the message is not cleared on switching between categories. Therefore, when the new category has a few posts, the message keeps showing.
This pull request updates `CursesProvider` as follows.
* Erase the post menu message in `printPostMenuMessage` (renamed from `printInCenter`).
* Show "Loading..." message in the post menu window on launch.
* Stop fetching posts on creating the post menu and call `ctgMenuCallback("All")` instead to consolidate the post fetch logic.
* Consolidate `ctgMenuCallback` logic to handle categories with and without unread posts.
* Replace `currentCategoryRead` and `numRead` with calculations using other fields.
I confirmed following things on Feednix with this …
> Erase post menu before printing message

- .github/workflows/c-cpp.yml
- .github/workflows/codeql-analysis.yml
GitHub workflows for Feednix started to fail because of a failure in `apt-get install` due to a stale index file.
This pull request fixes the failure by running `apt-get update` beforehand. I confirmed GitHub workflows with this change succeeded for [pull request builds in my fork](https://github.com/masaru-iritani/Feednix/actions?query=branch:update_apt).
> Run apt-get update in GitHub workflows

- src/CursesProvider.cpp
- src/CursesProvider.h
Feednix uses `system()` to launch a web browser. However, it has a security risk because a URL is passed to `system()` without any validation or sanitization. A website can make Feednix run any command via a malicious URL.
This change makes following changes.
- Replace `system()` using unreliable parameters with `fork()`.
- Skip suppressing the standard output in a console session to allow `O` key to launch a web browser in a console session.
- Replace "~" with `$HOME` because `fork` doesn't handle it.
- Remove an unused `CTRLD` variable.
I confirmed following things using Feednix with this change.
- Feednix can launch a web browser (Firefox) in a GUI session on `O` key without outputting any error message.
- Feednix can launch a web browser (w3m) in a console session on `O` key.
- …
> Fork instead of calling system
